### ISSUE TITLE
core-atm-plugin 

### ISSUE THREAD

**Issue by 1stFabOne** [jonasesser/athenaV5-migrations-issues#19]
![image](https://user-images.githubusercontent.com/77128064/233443022-b30f9c5d-6deb-4f58-b66e-db8aa687f224.png)

![image](https://user-images.githubusercontent.com/77128064/233443100-464a4d42-f419-4cce-ab52-0ef45289d81e.png)

![image](https://user-images.githubusercontent.com/77128064/233443158-50f8b873-beeb-4d58-8fa6-7aec9b052a13.png)

**Comment by RobsenReal** [comment]
![image](https://user-images.githubusercontent.com/109453939/234934512-c143bf08-c4e8-4a82-b074-1e24f52d11ac.png)
I don't have this error message. The ATM has been working since release in Framework 5.0.0 and 5.1.0.
